# Generated by Django 6.0.5 on 2026-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_fees_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='due',
            new_name='paid_fees',
        ),
        migrations.RenameField(
            model_name='fees',
            old_name='paid',
            new_name='total_fees',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='total',
        ),
        migrations.AlterField(
            model_name='fees',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
