# Generated by Django 6.0.5 on 2026-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_address_alter_userprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
